esphome:
    name: garden
    platform: ESP32
    board: nodemcu-32s

wifi:
    ssid: !secret wifi.ssid
    password: !secret wifi.password
    use_address: 192.168.88.54

ota:
    password: 12345678

web_server:

logger:
    level: DEBUG

interval:
  - interval: 1min
    then:
      - logger.log: "API call"

sensor:
  - platform: adc
    pin: GPIO33
    name: "Pot1"
    update_interval: 10s
    accuracy_decimals: 0
    attenuation: 11db
    unit_of_measurement: '%'
    filters:
      # 1.1v = in water
      # 2.94v = dry
      lambda: |-
        return (2.95 - x) * 100.0 / (2.95 - 1.1);

  - platform: adc
    pin: GPIO32
    name: "Pot2"
    update_interval: 10s
    accuracy_decimals: 0
    attenuation: 11db
    unit_of_measurement: '%'
    filters:
      # 1.1v = in water
      # 2.94v = dry
      lambda: |-
        return (2.95 - x) * 100.0 / (2.95 - 1.1);

  - platform: adc
    pin: GPIO35
    name: "Pot3"
    update_interval: 10s
    accuracy_decimals: 0
    attenuation: 11db
    unit_of_measurement: '%'
    filters:
      # 1.1v = in water
      # 2.94v = dry
      lambda: |-
        return (2.95 - x) * 100.0 / (2.95 - 1.1);


  - platform: adc
    pin: GPIO34
    name: "Pot4"
    update_interval: 10s
    accuracy_decimals: 0
    attenuation: 11db
    unit_of_measurement: '%'
    filters:
      # 1.1v = in water
      # 2.94v = dry
      lambda: |-
        return (2.95 - x) * 100.0 / (2.95 - 1.1);
    