esphome:
    name: garden
    platform: ESP32
    board: nodemcu-32s

wifi:
    ssid: !secret wifi.ssid
    password: !secret wifi.password
    use_address: 192.168.88.54

ota:
    password: !secret ota.password

web_server:

logger:
    level: DEBUG

# HTTP request component
http_request:
  useragent: esphome/device
  timeout: 10s

# Automation
interval:
  - interval: 10sec
    then:
      - logger.log: "API call"
      - http_request.post:
          url: !secret yndx.api.url
          headers:
            Content-Type: application/json
          verify_ssl: false
          json: |-
            root["pot1"] = id(Pot1).state;
      

sensor:
  - platform: adc
    pin: GPIO33
    name: "Pot1"
    id: "Pot1"
    update_interval: 1min
    accuracy_decimals: 0
    attenuation: 11db
    unit_of_measurement: '%'
    filters:
      lambda: |-
        return (2.95 - x) * 100.0 / (2.95 - 1.1);

  - platform: adc
    pin: GPIO32
    name: "Pot2"
    update_interval: 1min
    accuracy_decimals: 0
    attenuation: 11db
    unit_of_measurement: '%'
    filters:
      lambda: |-
        return (2.95 - x) * 100.0 / (2.95 - 1.1);

  - platform: adc
    pin: GPIO35
    name: "Pot3"
    update_interval: 1min
    accuracy_decimals: 0
    attenuation: 11db
    unit_of_measurement: '%'
    filters:
      lambda: |-
        return (2.95 - x) * 100.0 / (2.95 - 1.1);


  - platform: adc
    pin: GPIO34
    name: "Pot4"
    update_interval: 1min
    accuracy_decimals: 0
    attenuation: 11db
    unit_of_measurement: '%'
    filters:
      lambda: |-
        return (2.95 - x) * 100.0 / (2.95 - 1.1);
    