openapi: 3.0.0
info:
  title: Sample API
  version: 1.0.0
servers:
- url: https://<api-id>.apigw.yandexcloud.net
paths:
  /:
    post:
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: <functionId>
        service_account_id: <serviceAccountId>
